name: API CI
#on: [push]
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install
        shell: bash
        run: npm ci
      - name: run linter
        shell: bash
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:14
    services:
      mongo-e2e:
        image: mongo:4.4
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
          - 27018:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        shell: bash
        run: npm ci
      - name: run e2e
        shell: bash
        run: npm run test:e2e
        env:
          MONGO_DB_NAME: demo
          MONGO_URL: mongodb://admin:admin@mongo-e2e:27018?retryWrites=true&writeConcern=majority



